<?php
use Drupal\newsletter\Controller\NewsletterController;
use Drupal\newsletter\Model\Subscriber;

function newsletter_schema()
{
    $newsletterController = new NewsletterController();
    $base = $newsletterController->getCompanyController();

    if (isset($base)) {
        if (\Drupal::database()->schema()->tableExists(Subscriber::TABLE_SUBSCRIBER) == FALSE) {
            $schema[Subscriber::TABLE_SUBSCRIBER] = $base->setSchemaTableSubscriber();
        }

        if (isset($schema) && !empty($schema)) return $schema;
    }
}

function newsletter_theme($existing, $type, $theme, $path) {
    return [
        'inscription' => [
            'template' => 'newsletter--inscription',
            'variables' => [
                'form' => NULL,
                'msg' => NULL,
            ],
            'render element' => 'form'
        ]
    ];
}

//run update.php to execute this update
function newsletter_update_8101(&$sandbox)
{
    $newsletterController = new NewsletterController();
    $base = $newsletterController->getCompanyController();

    if (isset($base)) {
        if (\Drupal::database()->schema()->tableExists("newsletter_subscription")) {
            if (method_exists($base, 'setUpdate8101')) {
                \Drupal::logger('newsletter')->notice('[UPDATE] Déplacement des données de la table newsletter_subscription à la colonne dans la table newsletter_susbcriber.subscriptions');
                $base->setUpdate8101("newsletter_subscription");
            }

            //delete table subscription
            \Drupal::database()->schema()->dropTable("newsletter_subscription");
            \Drupal::logger('newsletter')->notice('[UPDATE] Suppression de l\'ancienne table newsletter_subscription');
        }
    }
}

//run update.php to execute this update
function newsletter_update_8102(&$sandbox)
{
    $newsletterController = new NewsletterController();
    $base = $newsletterController->getCompanyController();

    if (isset($base)) {
        if (\Drupal::database()->schema()->tableExists(Subscriber::TABLE_SUBSCRIBER)) {
            if (method_exists($base, 'setUpdate8102')) {
                \Drupal::logger('newsletter')->notice('[UPDATE] Ajout colonne pour le n° de mobile - C2E');
                $base->setUpdate8102();
            }
        }
    }
}