<?php

use Drupal\newsletter\NewsletterSubscriberRepository;
use Drupal\newsletter\SchemaTable\SchemaTableController;
use Drupal\newsletter\Update\UpdateController;

function newsletter_schema()
{
    $schemaTableController = new SchemaTableController();

    \Drupal::logger('newsletter')->notice($schemaTableController->currentSitename);

    $schemaTable = $schemaTableController->getSchemaTable();

    if (isset($schemaTable)) {
        if (\Drupal::database()->schema()->tableExists(NewsletterSubscriberRepository::TABLE_NAME) == FALSE) {
            $schema[NewsletterSubscriberRepository::TABLE_NAME] = $schemaTable->createNewsletterSubscriberSchemaTable();
            if (!empty($schema)) return $schema;
        }
    }
}

function newsletter_theme($existing, $type, $theme, $path) {
    return [
        'inscription' => [
            'template' => 'newsletter--inscription',
            'variables' => [
                'form' => NULL,
                'msg' => NULL,
            ],
            'render element' => 'form'
        ]
    ];
}

function newsletter_update_8101(&$sandbox)
{
    $updateController = new UpdateController();
    $update = $updateController->getUpdate();
    $update->setUpdate('8101');
}

function newsletter_update_8102(&$sandbox)
{
    $updateController = new UpdateController();
    $update = $updateController->getUpdate();
    $update->setUpdate('8102');
}

function newsletter_update_8103(&$sandbox)
{
    $updateController = new UpdateController();
    $update = $updateController->getUpdate();
    $update->setUpdate('8103');
}

function newsletter_update_8104(&$sandbox)
{
    $updateController = new UpdateController();
    $update = $updateController->getUpdate();
    $update->setUpdate('8104');
}

function newsletter_update_8105(&$sandbox)
{
    $updateController = new UpdateController();
    $update = $updateController->getUpdate();
    $update->setUpdate('8105');
}