<?php

function c2e_produits_theme($existing, $type, $theme, $path) {
    return [
        'liste' => [
            'template' => 'c2e-produits--list',
            'variables' => [
                'products' => NULL,
                'nbItem' => NULL
            ]
        ]
    ];
}

function c2e_produits_mail($key, &$message, $params)
{
    $message['headers']['Cc'] = $params['cc'];
    $message['from'] = $params['from'];
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['message'];
}