<?php
use \Drupal\c2e_produits\Controller;

function c2e_produits_theme($existing, $type, $theme, $path) {
    return [
        'liste' => [
            'template' => 'c2e-produits--list',
            'variables' => [
                'products' => NULL,
                'nbItem' => NULL
            ]
        ]
    ];
}

function c2e_produits_cron()
{
    \Drupal::logger('c2e_produits')->notice('[C2E PRODUITS] Lancement cron');

    $fluxRss = new Controller\FluxRssController();
    $fluxRss->generateFlux();
    $products = new Controller\ProductController();
    $products->checkProducts();

    \Drupal::state()->set('c2e_produits.last_run', REQUEST_TIME);

    \Drupal::logger('c2e_produits')->notice('[C2E PRODUITS] Cron terminé');
}

function c2e_produits_mail($key, &$message, $params)
{
    $message['from'] = $params['from'];
    $message['subject'] = $params['subject'];
    $message['body'][] = Html::escape($params['body']);
}