version: '3'

x-restart-always: &restart-always
  restart: always

services:
  web:
    image: nginx:stable
    volumes:
      - "./docker/web/etc/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
      - "./cleverage/docker/web/dev-entrypoint.sh:/dev-entrypoint.sh"
    entrypoint: /dev-entrypoint.sh
    command: nginx -g 'daemon off;'
    environment:
      DOCKER_HOST_UID: "${DOCKER_HOST_UID:-1000}"
      DOCKER_HOST_GID: "${DOCKER_HOST_GID:-1000}"
    <<: *restart-always
    labels:
      traefik: "true"
      traefik.http.services.web.loadbalancer.server.port: 80
      traefik.http.routers.web.rule: "HostRegexp(`{x:((.+).)?}${TRAEFIK_DOMAIN}`)"
      traefik.http.routers.web.priority: "2"
      traefik.http.routers.web.entrypoints: web,websecure
      traefik.http.routers.web.middlewares: extra_headers

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.cleverage
      cache_from:
        - php:7.1-fpm
    volumes:
      - ".:/var/www/html"
      - "./cleverage/docker/php/dev-entrypoint.sh:/dev-entrypoint.sh"
    entrypoint: /dev-entrypoint.sh
    command: php-fpm
    environment:
      COMPOSER_AUTH: '{"http-basic":{"repo.packagist.com":{"username":"token","password":"d84aa5a819bf0df1f7226bb9d3dc3d003f4b4d8c0ebf4a8245af58605c33"}}}'
      COMPOSER_HOME: /var/www/.composer
      DOCKER_HOST_UID: "${DOCKER_HOST_UID:-1000}"
      DOCKER_HOST_GID: "${DOCKER_HOST_GID:-1000}"
    networks:
      default:
        aliases:
          - php_internal
    <<: *restart-always

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
    command: ["--skip-log-bin"]
    <<: *restart-always

  mail:
    image: mailhog/mailhog
    networks:
      default:
        aliases:
          - mailhog_global
    <<: *restart-always
    labels:
      traefik: "true"
      traefik.http.services.mail.loadbalancer.server.port: 8025
      traefik.http.routers.mail.rule: "HostRegexp(`{x:mail(hog)?}.${TRAEFIK_DOMAIN}`)"
      traefik.http.routers.mail.entrypoints: web,websecure
      traefik.http.routers.mail.middlewares: extra_headers

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    volumes:
      - /sessions
    <<: *restart-always
    labels:
      traefik: "true"
      traefik.http.services.phpmyadmin.loadbalancer.server.port: 80
      traefik.http.routers.phpmyadmin.rule: "HostRegexp(`{x:php(myadmin)?}.${TRAEFIK_DOMAIN}`)"
      traefik.http.routers.phpmyadmin.entrypoints: web,websecure
      traefik.http.routers.phpmyadmin.middlewares: extra_headers

  traefik:
    image: traefik:${TRAEFIK_VERSION:-v2.5}
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
      TRAEFIK_DOMAIN: "${TRAEFIK_DOMAIN}"
      DEBUG: "true"
    entrypoint: ["/opt/traefik/dev-entrypoint.sh"]
    command: "traefik --configfile /etc/traefik.yml"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./cleverage/docker/traefik:/opt/traefik:ro
      - tls_certs:/etc/ssl/private
    labels:
      # add extra headers with headers middlewares
      traefik.http.middlewares.extra_headers.headers.stsSeconds: "${TRAEFIK_HSTS_SECONDS:-30}"
      traefik.http.middlewares.extra_headers.headers.stsIncludeSubdomains: "${TRAEFIK_HSTS_INCLUDE:-true}"
      traefik.http.middlewares.extra_headers.headers.stsPreload: "${TRAEFIK_HSTS_PRELOAD:-true}"
      traefik.http.middlewares.extra_headers.headers.forceSTSHeader: "${TRAEFIK_HSTS_FORCE:-true}"
      traefik.http.middlewares.extra_headers.headers.frameDeny: "${TRAEFIK_FRAME_DENY:-false}"
      traefik.http.middlewares.extra_headers.headers.customFrameOptionsValue: "${TRAEFIK_FRAME_OPTIONS:-sameorigin}"
      traefik.http.middlewares.extra_headers.headers.contentTypeNosniff: "${TRAEFIK_NO_SNIFF:-true}"
      traefik.http.middlewares.extra_headers.headers.browserXssFilter: "${TRAEFIK_XSS_FILTER:-true}"
      # exposes traefik publicly
      traefik: "true"
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik.entrypoints: web,websecure
      traefik.http.routers.traefik.middlewares: extra_headers
    <<: *restart-always

volumes:
  db_data:
    driver: local
  tls_certs:
    driver: local
