version: '3'
services:
  web:
      networks:
        - webgateway
        - default
      image: nginx:1.13-alpine
      volumes:
        - "$PWD../../../docker/web/etc/nginx.conf:/etc/nginx/nginx.conf"
        - "$PWD../../../docker/web/etc/default.conf:/etc/nginx/conf.d/default.conf"
        - "$PWD../../../:/var/www/html"
      labels:
        traefik.docker.network: "webgateway"
        traefik.enable: true
  php:
      build: ../../docker/php
      command: php-fpm --allow-to-run-as-root
      volumes:
        - "$PWD../../../:/var/www/html"
        - "$PWD../../../docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      networks:
        - webgateway
        - default
  db:
      image: mariadb:10.1.2
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: $COMPOSE_PROJECT_NAME
        MYSQL_USER: $COMPOSE_PROJECT_NAME
        MYSQL_PASSWORD: $COMPOSE_PROJECT_NAME
      volumes:
        - "$PWD../../../:/var/www/html"
        - db_data:/var/lib/mysql
      labels:
        traefik.docker.network: "webgateway"
        traefik.enable: true

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.7.9-1
      networks:
        - webgateway
        - default
      volumes:
          - /sessions
      labels:
        traefik.docker.network: "webgateway"
        traefik.enable: true

  mail:
      image: mailhog/mailhog
      networks:
        - webgateway
        - default
      labels:
        traefik.docker.network: "webgateway"
        traefik.enable: true
        traefik.port: 8025

  bundle:
      build: ../../docker/deployment
      working_dir: /project
      volumes:
        - "$PWD:/project"

volumes:
  db_data:
    driver: local

networks:
  webgateway:
    external: true
