<?php

namespace Drupal\offres_prestataires\Helper;

class Taxonomy
{
    public function title()
    {
        return [
            'Monsieur' => 'Monsieur',
            'Madame' => 'Madame',
            'Mademoiselle' => 'Mademoiselle',
            'Professeur' => 'Professeur',
            'Docteur' => 'Docteur',
        ];
    }

    public function studyLvl()
    {
        return [
            '1' => 'Aucun / Autre',
            '2' => 'Autodidacte',
            '3' => 'Brevet',
            '4' => 'CAP/BEP',
            '5' => 'Bac',
            '6' => 'Bac +1',
            '7' => 'Bac +2',
            '8' => 'Bac +3',
            '9' => 'Bac +4',
            '10' => 'Bac +5',
            '11' => 'Bac +6',
            '12' => 'Doctorat ou équivalent',
            '13' => 'Post-doctorat ou équivalent',
            '14' => 'Inconnu ou non-renseigné',
            '15' => 'BTS',
        ];
    }

    public function currentSituation()
    {
        return [
            '1' => 'En poste',
            '2' => 'Sans emploi',
            '3' => 'En période d\'essai',
            '4' => 'En préavis',
        ];
    }

    public function currentSearch()
    {
        return [
            '1' => 'En veille passive',
            '2' => 'En veille active',
            '3' => 'Passe un premier entretien',
            '4' => 'Passe un deuxième entretien',
            '5' => 'Attend des propositions',
            '6' => 'A reçu des propositions',
            '7' => 'Pas/plus en recherche pour le moment',
        ];
    }

    public function disponibility()
    {
        return [
            '1' => 'Disponible',
            '2' => 'Préavis à 1 mois',
            '3' => 'Préavis à 2 mois',
            '4' => 'Préavis à 3 mois',
            '5' => 'Préavis à négocier',
            '6' => 'Non-renseigné',
        ];
    }

    public function offerType()
    {
        return [
            '1' => 'Non-renseigné',
            '2' => 'CDI - Contrat à durée indéterminée',
            '3' => 'CDD - Contrat à durée déterminée',
            '4' => 'CTT - Contrat de travail temporaire',
            '5' => 'Contrat d\'apprentissage',
            '6' => 'Stage',
            '7' => 'Contrat aidé',
            '8' => 'Indépendants/freelances',
            '9' => 'Contrat de sous-traitance SSII',
            '10' => 'Contrat statutaire',
            '11' => 'Contrat de portage salarial',
        ];
    }

    public function activityType()
    {
        return [
            '1' => 'Banque / Assurance / Finance',
            '2' => 'Construction / BTP',
            '3' => 'Distribution',
            '4' => 'Industries',
            '5' => 'Immobilier',
            '6' => 'IT / Télécom / Internet',
            '7' => 'Services publics / Administrations',
            '8' => 'Services',
            '9' => 'Inconnu ou non-renseigné',
        ];
    }

    public function companyType()
    {
        return [
            '1' => 'PME/PMI',
            '2' => 'ETI',
            '3' => 'Grands groupes',
            '4' => 'SSII',
            '5' => 'Organisation',
            '6' => 'Autre',
            '7' => 'Inconnu ou non-renseigné',
            '8' => 'Editeur',
            '9' => 'Start-up',
        ];
    }

    public function lang()
    {
        return [
            'af' => 'Afrikaans',
            'sq' => 'Albanais',
            'de' => 'Allemand',
            'en' => 'Anglais',
            'ar' => 'Arabe',
            'bn' => 'Bengalî',
            'be' => 'Biélorusse',
            'my' => 'Birman',
            'bs' => 'Bosnien',
            'bg' => 'Bulgare',
            'zh' => 'Chinois',
            'ko' => 'Coréen',
            'hr' => 'Croate',
            'da' => 'Danois',
            'gd' => 'Écossais',
            'es' => 'Espagnol',
            'eo' => 'Espéranto',
            'et' => 'Estonien',
            'fi' => 'Finnois',
            'fr' => 'Français',
            'cy' => 'Gallois',
            'ka' => 'Géorgien',
            'el' => 'Grec moderne',
            'he' => 'Hébreu',
            'hi' => 'Hindî',
            'hu' => 'Hongrois',
            'id' => 'Indonésien',
            'ga' => 'Irlandais',
            'is' => 'Islandais',
            'it' => 'Italien',
            'ja' => 'Japonais',
            'km' => 'Khmer',
            'ku' => 'Kurde',
            'la' => 'Latin',
            'lv' => 'Letton',
            'lt' => 'Lituanien',
            'mk' => 'Macédonien',
            'mg' => 'Malgache',
            'mo' => 'Moldave',
            'mn' => 'Mongol',
            'nl' => 'Néerlandais',
            'ne' => 'Népalais',
            'no' => 'Norvégien',
            'ug' => 'Ouïghour',
            'ur' => 'Ourdou',
            'uz' => 'Ouzbek',
            'fa' => 'Persan',
            'pl' => 'Polonais',
            'pt' => 'Portugais',
            'rm' => 'Romanche',
            'ro' => 'Roumain',
            'ru' => 'Russe',
            'sa' => 'Sanskrit',
            'sr' => 'Serbe',
            'sd' => 'Sindhi',
            'sk' => 'Slovaque',
            'sl' => 'Slovène',
            'su' => 'Soundanais',
            'sv' => 'Suédois',
            'sw' => 'Swahili',
            'ta' => 'Tamoul',
            'cs' => 'Tchèque',
            'ce' => 'Tchétchène',
            'th' => 'Thaï',
            'bo' => 'Tibétain',
            'ts' => 'Tsonga',
            'tr' => 'Turc',
            'uk' => 'Ukrainien',
            'vi' => 'Vietnamien',
            'wa' => 'Wallon',
            'wo' => 'Wolof',
            'ii' => 'Yi',
            'yi' => 'Yiddish',
        ];
    }

    public function langLvl()
    {
        return [
            '1' => 'Débutant',
            '2' => 'Elémentaire (A1)',
            '3' => 'Elémentaire supérieur (A1-A2)',
            '4' => 'Intermédiaire inférieur (A2)',
            '5' => 'Intermédiaire (A2-B1)',
            '6' => 'Intermédiaire supérieur (B1)',
            '7' => 'Avancé (B1-B2)',
            '8' => 'Très avancé (C1)',
            '9' => 'Proche de natif (C1-C2)',
            '10' => 'Non renseigné',
        ];
    }

    public function country()
    {
        return [
            'AF' => 'AFGHANISTAN',
            'ZA' => 'AFRIQUE DU SUD',
            'AX' => 'ÅLAND, ÎLES',
            'AL' => 'ALBANIE',
            'DZ' => 'ALGÉRIE',
            'DE' => 'ALLEMAGNE',
            'AD' => 'ANDORRE',
            'AO' => 'ANGOLA',
            'AI' => 'ANGUILLA',
            'AQ' => 'ANTARCTIQUE',
            'AG' => 'ANTIGUA-ET-BARBUDA',
            'SA' => 'ARABIE SAOUDITE',
            'AR' => 'ARGENTINE',
            'AM' => 'ARMÉNIE',
            'AW' => 'ARUBA',
            'AU' => 'AUSTRALIE',
            'AT' => 'AUTRICHE',
            'AZ' => 'AZERBAÏDJAN',
            'BS' => 'BAHAMAS',
            'BH' => 'BAHREÏN',
            'BD' => 'BANGLADESH',
            'BB' => 'BARBADE',
            'BY' => 'BÉLARUS',
            'BE' => 'BELGIQUE',
            'BZ' => 'BELIZE',
            'BJ' => 'BÉNIN',
            'BM' => 'BERMUDES',
            'BT' => 'BHOUTAN',
            'BO' => 'BOLIVIE, ÉTAT PLURINATIONAL DE',
            'BQ' => 'BONAIRE, SAINT-EUSTACHE ET SABA',
            'BA' => 'BOSNIE-HERZÉGOVINE',
            'BW' => 'BOTSWANA',
            'BV' => 'BOUVET, ÎLE',
            'BR' => 'BRÉSIL',
            'BN' => 'BRUNEI DARUSSALAM',
            'BG' => 'BULGARIE',
            'BF' => 'BURKINA FASO',
            'BI' => 'BURUNDI',
            'KY' => 'CAÏMANS, ÎLES',
            'KH' => 'CAMBODGE',
            'CM' => 'CAMEROUN',
            'CA' => 'CANADA',
            'CV' => 'CAP-VERT',
            'CF' => 'CENTRAFRICAINE, RÉPUBLIQUE',
            'CL' => 'CHILI',
            'CN' => 'CHINE',
            'CX' => 'CHRISTMAS, ÎLE',
            'CY' => 'CHYPRE',
            'CC' => 'COCOS (KEELING), ÎLES',
            'CO' => 'COLOMBIE',
            'KM' => 'COMORES',
            'CG' => 'CONGO',
            'CD' => 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU',
            'CK' => 'COOK, ÎLES',
            'KR' => 'CORÉE, RÉPUBLIQUE DE',
            'KP' => 'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE',
            'CR' => 'COSTA RICA',
            'CI' => 'CÔTE D\'IVOIRE',
            'HR' => 'CROATIE',
            'CU' => 'CUBA',
            'CW' => 'CURAÇAO',
            'DK' => 'DANEMARK',
            'DJ' => 'DJIBOUTI',
            'DO' => 'DOMINICAINE, RÉPUBLIQUE',
            'DM' => 'DOMINIQUE',
            'EG' => 'ÉGYPTE',
            'SV' => 'EL SALVADOR',
            'AE' => 'ÉMIRATS ARABES UNIS',
            'EC' => 'ÉQUATEUR',
            'ER' => 'ÉRYTHRÉE',
            'ES' => 'ESPAGNE',
            'EE' => 'ESTONIE',
            'US' => 'ÉTATS-UNIS',
            'ET' => 'ÉTHIOPIE',
            'FK' => 'FALKLAND, ÎLES (MALVINAS',
            'FO' => 'FÉROÉ, ÎLES',
            'FJ' => 'FIDJI',
            'FI' => 'FINLANDE',
            'FR' => 'FRANCE',
            'GA' => 'GABON',
            'GM' => 'GAMBIE',
            'GE' => 'GÉORGIE',
            'GS' => 'GÉORGIE DU SUD-ET-LES ÎLES SANDWICH DU SUD',
            'GH' => 'GHANA',
            'GI' => 'GIBRALTAR',
            'GR' => 'GRÈCE',
            'GD' => 'GRENADE',
            'GL' => 'GROENLAND',
            'GP' => 'GUADELOUPE',
            'GU' => 'GUAM',
            'GT' => 'GUATEMALA',
            'GG' => 'GUERNESEY',
            'GN' => 'GUINÉE',
            'GQ' => 'GUINÉE ÉQUATORIALE',
            'GW' => 'GUINÉE-BISSAU',
            'GY' => 'GUYANA',
            'GF' => 'GUYANE FRANÇAISE',
            'HT' => 'HAÏTI',
            'HM' => 'HEARD-ET-ÎLES MACDONALD, ÎLE',
            'HN' => 'HONDURAS',
            'HK' => 'HONG KONG',
            'HU' => 'HONGRIE',
            'IM' => 'ÎLE DE MAN',
            'UM' => 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS',
            'VG' => 'ÎLES VIERGES BRITANNIQUES',
            'VI' => 'ÎLES VIERGES DES ÉTATS-UNIS',
            'IN' => 'INDE',
            'ID' => 'INDONÉSIE',
            'IR' => 'IRAN, RÉPUBLIQUE ISLAMIQUE D',
            'IQ' => 'IRAQ',
            'IE' => 'IRLANDE',
            'IS' => 'ISLANDE',
            'IL' => 'ISRAËL',
            'IT' => 'ITALIE',
            'JM' => 'JAMAÏQUE',
            'JP' => 'JAPON',
            'JE' => 'JERSEY',
            'JO' => 'JORDANIE',
            'KZ' => 'KAZAKHSTAN',
            'KE' => 'KENYA',
            'KG' => 'KIRGHIZISTAN',
            'KI' => 'KIRIBATI',
            'KW' => 'KOWEÏT',
            'LA' => 'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE',
            'LS' => 'LESOTHO',
            'LV' => 'LETTONIE',
            'LB' => 'LIBAN',
            'LR' => 'LIBÉRIA',
            'LY' => 'LIBYE',
            'LI' => 'LIECHTENSTEIN',
            'LT' => 'LITUANIE',
            'LU' => 'LUXEMBOURG',
            'MO' => 'MACAO',
            'MK' => 'MACÉDOINE, L\'EX-RÉPUBLIQUE YOUGOSLAVE DE',
            'MG' => 'MADAGASCAR',
            'MY' => 'MALAISIE',
            'MW' => 'MALAWI',
            'MV' => 'MALDIVES',
            'ML' => 'MALI',
            'MT' => 'MALTE',
            'MP' => 'MARIANNES DU NORD, ÎLES',
            'MA' => 'MAROC',
            'MH' => 'MARSHALL, ÎLES',
            'MQ' => 'MARTINIQUE',
            'MU' => 'MAURICE',
            'MR' => 'MAURITANIE',
            'YT' => 'MAYOTTE',
            'MX' => 'MEXIQUE',
            'FM' => 'MICRONÉSIE, ÉTATS FÉDÉRÉS DE',
            'MD' => 'MOLDOVA, RÉPUBLIQUE DE',
            'MC' => 'MONACO',
            'MN' => 'MONGOLIE',
            'ME' => 'MONTÉNÉGRO',
            'MS' => 'MONTSERRAT',
            'MZ' => 'MOZAMBIQUE',
            'MM' => 'MYANMAR',
            'NA' => 'NAMIBIE',
            'NR' => 'NAURU',
            'NP' => 'NÉPAL',
            'NI' => 'NICARAGUA',
            'NE' => 'NIGER',
            'NG' => 'NIGÉRIA',
            'NU' => 'NIUÉ',
            'NF' => 'NORFOLK, ÎLE',
            'NO' => 'NORVÈGE',
            'NC' => 'NOUVELLE-CALÉDONIE',
            'NZ' => 'NOUVELLE-ZÉLANDE',
            'IO' => 'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L',
            'OM' => 'OMAN',
            'UG' => 'OUGANDA',
            'UZ' => 'OUZBÉKISTAN',
            'PK' => 'PAKISTAN',
            'PW' => 'PALAOS',
            'PS' => 'PALESTINIEN OCCUPÉ, TERRITOIRE',
            'PA' => 'PANAMA',
            'PG' => 'PAPOUASIE-NOUVELLE-GUINÉE',
            'PY' => 'PARAGUAY',
            'NL' => 'PAYS-BAS',
            'PE' => 'PÉROU',
            'PH' => 'PHILIPPINES',
            'PN' => 'PITCAIRN',
            'PL' => 'POLOGNE',
            'PF' => 'POLYNÉSIE FRANÇAISE',
            'PR' => 'PORTO RICO',
            'PT' => 'PORTUGAL',
            'QA' => 'QATAR',
            'RE' => 'RÉUNION',
            'RO' => 'ROUMANIE',
            'GB' => 'ROYAUME-UNI',
            'RU' => 'RUSSIE, FÉDÉRATION DE',
            'RW' => 'RWANDA',
            'EH' => 'SAHARA OCCIDENTAL',
            'BL' => 'SAINT-BARTHÉLEMY',
            'SH' => 'SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA',
            'LC' => 'SAINTE-LUCIE',
            'KN' => 'SAINT-KITTS-ET-NEVIS',
            'SM' => 'SAINT-MARIN',
            'SX' => 'SAINT-MARTIN (PARTIE NÉERLANDAISE',
            'MF' => 'SAINT-MARTIN(PARTIE FRANÇAISE',
            'PM' => 'SAINT-PIERRE-ET-MIQUELON',
            'VA' => 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN',
            'VC' => 'SAINT-VINCENT-ET-LES GRENADINES',
            'SB' => 'SALOMON, ÎLES',
            'WS' => 'SAMOA',
            'AS' => 'SAMOA AMÉRICAINES',
            'ST' => 'SAO TOMÉ-ET-PRINCIPE',
            'SN' => 'SÉNÉGAL',
            'RS' => 'SERBIE',
            'SC' => 'SEYCHELLES',
            'SL' => 'SIERRA LEONE',
            'SG' => 'SINGAPOUR',
            'SK' => 'SLOVAQUIE',
            'SI' => 'SLOVÉNIE',
            'SO' => 'SOMALIE',
            'SD' => 'SOUDAN',
            'SS' => 'SOUDAN DU SUD',
            'LK' => 'SRI LANKA',
            'SE' => 'SUÈDE',
            'CH' => 'SUISSE',
            'SR' => 'SURINAME',
            'SJ' => 'SVALBARD ET ÎLE JAN MAYEN',
            'SZ' => 'SWAZILAND',
            'SY' => 'SYRIENNE, RÉPUBLIQUE ARABE',
            'TJ' => 'TADJIKISTAN',
            'TW' => 'TAÏWAN, PROVINCE DE CHINE',
            'TZ' => 'TANZANIE, RÉPUBLIQUE-UNIE DE',
            'TD' => 'TCHAD',
            'CZ' => 'TCHÈQUE, RÉPUBLIQUE',
            'TF' => 'TERRES AUSTRALES FRANÇAISES',
            'TH' => 'THAÏLANDE',
            'TL' => 'TIMOR-LESTE',
            'TG' => 'TOGO',
            'TK' => 'TOKELAU',
            'TO' => 'TONGA',
            'TT' => 'TRINITÉ-ET-TOBAGO',
            'TN' => 'TUNISIE',
            'TM' => 'TURKMÉNISTAN',
            'TC' => 'TURKS-ET-CAÏCOS, ÎLES',
            'TR' => 'TURQUIE',
            'TV' => 'TUVALU',
            'UA' => 'UKRAINE',
            'UY' => 'URUGUAY',
            'VU' => 'VANUATU',
            'VE' => 'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU',
            'VN' => 'VIET NAM',
            'WF' => 'WALLIS ET FUTUNA',
            'YE' => 'YÉMEN',
            'ZM' => 'ZAMBIE',
            'ZW' => 'ZIMBABWE',
        ];
    }
}