<?php
/*
 * @file
 * code for resume module
*/


function recherchePdf_theme()
{
    return [
        'recherche' => [
            'render element' => 'form',
            'variables' => [
                'ref_produit' => NULL,
                'lot_produit' => NULL,
                'msg' => NULL,
            ],
        ],
        'resultat' => [
            'render element' => 'form',
            'variables' => [
                'fiche_pdf' => NULL,
            ],
        ],
    ];


}
?>