<?php
/*
 * @file
 * code for resume module
*/


function recherchePdf_theme()
{
    return [
        'recherche' => [
            'render element' => 'form',
            'variables' => [
                'ref_produit' => NULL,
                'lot_produit' => NULL,
                'msg' => NULL,
            ],
        ],
        'resultat' => [
            'render element' => 'form',
            'variables' => [
                'fiche_pdf' => NULL,
            ],
        ],
    ];
}

function recherchePdf_mail($key, &$message, $params) {

    // E-mail formatting will be exactly as below, so do not use indenting!
    $body = $params['body'];
    $message['from'] = $params['from'];
    $message['subject'] = $params['subject'];

    $message['body'][] = Drupal\Core\Mail\MailFormatHelper::htmlToText($body);
}

?>
