<?php

/**
 * @file
 * Sema block module file
 */


/**
 * Implements hook_theme().
 */
function sema_block_theme($existing, $type, $theme, $path)
{
  return [
    'sema_block__find_our_products' => [
      'template' => 'sema-block--find-our-products',
      'variables' => [
        'content' => [],
      ],

    ],
    'sema_block__newsletter' => [
      'template' => 'sema-block--newsletter',
      'variables' => [
        'content' => [],
      ],
    ],
    'sema_block__instagram' => [
      'template' => 'sema-block--instagram',
      'variables' => [
        'content' => [],
      ],
    ],
    'sema_block__menu_footer' => [
      'template' => 'sema-block--menu-footer',
      'variables' => [
        'content' => [],
      ],
    ],
  ];
}
