<?php

/**
 * @file
 * Sema block module file
 */


/**
 * Implements hook_theme().
 */
function sema_block_theme($existing, $type, $theme, $path)
{
  return [
    'sema_block__find_our_products' => [
      'template' => 'sema-block--find-our-products',
      'variables' => [
        'content' => [],
      ],

    ],
    'sema_block__newsletter' => [
      'template' => 'sema-block--newsletter',
      'variables' => [
        'content' => [],
      ],
    ],
    'sema_block__instagram' => [
      'template' => 'sema-block--instagram',
      'variables' => [
        'content' => [],
      ],
    ],
    'sema_block__menu_footer' => [
      'template' => 'sema-block--menu-footer',
      'variables' => [
        'content' => [],
      ],
    ],
  ];
}


/**
 * Implements hook_preprocess_block().
 * @param $variables
 */
function sema_block_preprocess_block(&$variables)
{
  if ($variables['plugin_id'] == 'drupal_synapse_search_location_block') {
    $myConfigPage = \Drupal\config_pages\Entity\ConfigPages::config('page_find_our_products');
    if (!empty($myConfigPage)) {
      $variables['content']['#sema']['description'] = $myConfigPage->get('field_description')->value;
      $variables['content']['#sema']['title'] = $myConfigPage->get('field_title')->value;

      $view_builder = \Drupal::entityTypeManager()
        ->getViewBuilder($myConfigPage->get('field_main_picture')->entity->getEntityTypeId());

      $variables['content']['#sema']['mainPicture'] = $view_builder->view($myConfigPage->get('field_main_picture')->entity, 'default');
    }
  }
}
