<?php

function recherche_pdf_theme()
{
    return [
        'pdf-search--block' => [
            'template' => "recherche-pdf--pdf-search--block",
            'variables' => [
                'form' => NULL,
                'error' => NULL,
            ],
            'render element' => 'form',
        ],
        'pdf-list--page' => [
            'template' => "recherche-pdf--pdf-list--page",
            'variables' => [
                'pdfFiles' => NULL,
            ],
        ],
    ];
}

function recherche_pdf_mail($key, &$message, $params)
{
    $message['headers']['Cc'] = $params['cc'];
    $message['from'] = $params['from'];
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['message'];
}


?>
