<?php

function turbocar_preprocess_html(&$variables) {
    // Setup Google Webmasters Verification Meta Tag
    $google_site_verification = [
        '#tag' => 'meta',
        '#attributes' => [
            'name' => 'google-site-verification',
            'content' => 'ZVBUstDGm2AhPGw7sH77QVq_IYLN1',
        ],
    ];
    // Add Google Webmasters Verification Meta Tag to head
    $variables['page']['#attached']['html_head'][] = [$google_site_verification, 'google-site-verification'];
};