global:
  sendAnonymousUsage: false
  checkNewVersion: false
accessLog: true
log:
  level: ERROR
api:
  insecure: true
  dashboard: true
  debug: true
providers:
  file:
    filename: /opt/traefik/tls.yml
    watch: true
  docker:
    constraints: "Label(`traefik`, `true`)"
    defaultRule: "HostRegexp(`{{ trimPrefix `/` .Name | replace `-%COMPOSE_PROJECT_NAME%` `` | replace `%COMPOSE_PROJECT_NAME%-` `` }}.%TRAEFIK_DOMAIN%`)"
    watch: true
entryPoints:
  web:
    address: ":80"
    # @TODO enable this once 443 port is routed on the AWS virtual machine
    http:
      redirections:
        entryPoint:
          scheme: https
          to: websecure
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default
serversTransport:
  insecureSkipVerify: true
