# Schema for the configuration files of the private module.

action.configuration.private_content_make_public:
  type: action_configuration_default
  label: 'Make content public configuration'

action.configuration.private_content_make_private:
  type: action_configuration_default
  label: 'Make content private configuration'

node.type.*.third_party.private_content:
  type: mapping
  label: 'Per-content type private settings'
  mapping:
    private:
      type: integer
      label: 'Private visibility on the form'
