<?php

use Symfony\Component\Process\Process;
use Drupal\offres_emploi\Config\Config;
use Drupal\offres_emploi\Helper\OffresEmploiUpdate;

function offres_emploi_theme($existing, $type, $theme, $path) {
    $conf = new Config();
    return [
        'offres_emploi--list' => [
            'variables' => [
                'offers' => NULL,
                'filter' => NULL
            ]
        ],
        'offres_emploi--annonce' => [
            'variables' => [
                'offer' => NULL,
                'sirh_url' => $conf->getSirhUrl(),
            ]
        ]
    ];
}

function offres_emploi_cron()
{
    \Drupal::logger('offres_emploi')->notice('[OFFRES EMPLOI] Lancement cron');

    $url = \Drupal::request()->getHost();
    $path = dirname(DRUPAL_ROOT);

    $process = new Process( 'php ' . $path . '/vendor/bin/drupal --uri='. $url . ' offres_emploi:import');
    $process->run();


    if (!$process->isSuccessful()) {
        \Drupal::logger('offres_emploi')->error('Erreur dans l import des offres => drupal command failed');
    }

    // Update last run.
    \Drupal::state()->set('offres_emploi.last_run', REQUEST_TIME);

    \Drupal::logger('offres_emploi')->notice('[OFFRES EMPLOI] Cron terminé');
}

//run update.php to execute this update
function offres_emploi_update_8101(&$sandbox)
{
    $update = new OffresEmploiUpdate();
    $update->update8101();
}

//run update.php to execute this update
function offres_emploi_update_8102(&$sandbox)
{
    $update = new OffresEmploiUpdate();
    $update->update8102();
}