version: '3'
services:
  web:
      image: nginx:1.13-alpine
      volumes:
        - "$PWD../../../docker/web/etc/nginx.conf:/etc/nginx/nginx.conf"
        - "$PWD../../../docker/web/etc/default.conf:/etc/nginx/conf.d/default.conf"
        - "$PWD../../../:/var/www/html"
      networks:
        webgateway:
          aliases:
            - web_tbc
        internal:
          aliases:
            - web_internal
      labels:
        traefik.docker.network: "webgateway"
        traefik.enable: true
  php:
      build: ../../docker/php
      command: php-fpm --allow-to-run-as-root
      volumes:
        - "$PWD../../../:/var/www/html"
        - "$PWD../../../docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      environment:
        PHP_IDE_CONFIG: "serverName=drupal"
      networks:
        webgateway:
          aliases:
            - php_tbc
        internal:
          aliases:
            - php_internal
  db:
      image: mariadb:10.1.2
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: $COMPOSE_PROJECT_NAME
        MYSQL_USER: $COMPOSE_PROJECT_NAME
        MYSQL_PASSWORD: $COMPOSE_PROJECT_NAME
      volumes:
        - "$PWD../../../:/var/www/html"
        - db_data:/var/lib/mysql
      networks:
        webgateway:
          aliases:
            - db_tbc
        internal:
          aliases:
            - db_internal
      labels:
        traefik.docker.network: "webgateway"
        traefik.enable: true

  phpmyadmin:
      build: ../../docker/phpmyadmin
      environment:
        PMA_HOST: db_internal
      volumes:
          - /sessions
      networks:
        webgateway:
          aliases:
            - phpmyadmin_tbc
        internal:
          aliases:
            - phpmyadmin_internal
      labels:
        traefik.docker.network: "webgateway"
        traefik.enable: true

  bundle:
      build: ../../docker/deployment
      working_dir: /project
      volumes:
        - "$PWD:/project"

volumes:
  db_data:
    driver: local

networks:
  webgateway:
    external: true
  internal:
    external: false